language: python

matrix:
    include:
        - python: 3.6
          env: TOXENV=django20
        - python: 3.6
          env: TOXENV=django21
        - python: 3.6
          env: TOXENV=django20-no-sites

install:
  - pip install tox

script: tox
