[tox]
envlist =
    py38-django40
    py38-django40-no-sites
    py311-django41
    py311-django41-no-sites
    py311-django42
    py311-django42-no-sites
    py311-django50
    py311-django50-no-sites

[testenv]
commands = .

[testenv:py38-django40]
deps = -rultracache/tests/requirements/40.txt
commands = python manage.py test ultracache.tests{posargs} --nomigrations --settings=ultracache.tests.settings.40

[testenv:py38-django40-no-sites]
deps = -rultracache/tests/requirements/40.txt
commands = python manage.py test ultracache.tests{posargs} --nomigrations --settings=ultracache.tests.settings.40_no_sites

[testenv:py311-django41]
deps = -rultracache/tests/requirements/41.txt
commands = python manage.py test ultracache.tests{posargs} --nomigrations --settings=ultracache.tests.settings.41

[testenv:py311-django41-no-sites]
deps = -rultracache/tests/requirements/41.txt
commands = python manage.py test ultracache.tests{posargs} --nomigrations --settings=ultracache.tests.settings.41_no_sites

[testenv:py311-django42]
deps = -rultracache/tests/requirements/42.txt
commands = python manage.py test ultracache.tests{posargs} --nomigrations --settings=ultracache.tests.settings.42

[testenv:py311-django42-no-sites]
deps = -rultracache/tests/requirements/42.txt
commands = python manage.py test ultracache.tests{posargs} --nomigrations --settings=ultracache.tests.settings.42_no_sites

[testenv:py311-django50]
deps = -rultracache/tests/requirements/50.txt
commands = python manage.py test ultracache.tests{posargs} --nomigrations --settings=ultracache.tests.settings.50

[testenv:py311-django50-no-sites]
deps = -rultracache/tests/requirements/50.txt
commands = python manage.py test ultracache.tests{posargs} --nomigrations --settings=ultracache.tests.settings.50_no_sites
